import streamlit as st

from src.data_processes.data_ingestion import ingest_data
from src.langgraph_things.workflow import workflow
from src.langgraph_things.graph_state_init import initial_graph_state

def run():
    st.set_page_config(page_title="Streamlit GraphRAG", layout="centered")
    st.title("GraphRAG Assistant")
    # st.caption("")

    with st.sidebar:
        st.header("Data Management")
        st.write("Has new data been added?")
        if st.button("Run Data Ingestion & Processing"):
            with st.spinner("Ingesting and processing data..."):
                try:
                    ingest_data()
                    st.success("Data ingestion complete!")
                except Exception as e:
                    st.error(f"Error during ingestion: {str(e)}")


    if "messages" not in st.session_state:
        st.session_state.messages = [
            {"role": "assistant", "content": "Hi, I'm the GraphRag Chatbot!  How can I help you?"},
        ]

    # Display Chat History
    for message in st.session_state.messages:
        with st.chat_message(message["role"]):
            st.markdown(message["content"])

    # User Input
    if prompt := st.chat_input("Enter your question?"):

        with st.chat_message("user"):
            st.markdown(prompt)
        st.session_state.messages.append({"role": "user", "content": prompt})

    # --- Run Workflow Logic ---
        with st.chat_message("assistant"):

            final_answer = "No answer generated."
            
            with st.status("Processing request...", expanded=True) as status:
                try:
                    # Initialize your graph state
                    state = initial_graph_state()
                    state["question"] = prompt

                    # Stream the workflow
                    for output in workflow.stream(state):
                        for key, value in output.items():
                            st.write(f"Finished running: **{key}**") # saving the names of steps taken
                            
                            if 'generated_answer' in value:
                                final_answer = value['generated_answer']['answer']
                    
                    status.update(label="Complete", state="complete", expanded=False)
                    
                except Exception as e:
                    st.error(f"An error occurred: {str(e)}")
                    status.update(label="Error", state="error")
  
            
            # printing answer
            if final_answer:
                st.markdown(final_answer)
                st.session_state.messages.append({"role": "assistant", "content": final_answer})
            else:
                st.warning("No answer was generated by the workflow.")
